name: Container
on: push


jobs:
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: mrtnsgs/node-api:1.0
        ports:
          - 3001:3000
    container:
      image: node:13.5.0-alpine3.10
    steps:
      - name: Post a user
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username\": \"hello\",\"address\": \"dwded\"}'"
      - name: Get Users
        run: curl http://localhost:3001/api/user
